### ISSUE TITLE
This is not Issue..

### ISSUE THREAD

**Issue by pranavlathigara** [lguipeng/BubbleView#1]
Hii...
First of all this is great library for chat view
so thank you for this 

but i have to implement this in my chat application so i want to use two type of  layout which has two different arrow style...

**Comment by lguipeng** [comment]
yeap, you can change arrow style and call  requestLayout in BubbleView

**Comment by srikanthkancheti** [comment]
How can i get BubbleLayout tooltip on bottom right ?

**Comment by lguipeng** [comment]
it is supported. @srikanthkancheti
