### ISSUE TITLE
BubbleView cannot show complete

### ISSUE THREAD

**Issue by JarvanChen** [lguipeng/BubbleView#10]
![device-2017-05-03-175732](https://cloud.githubusercontent.com/assets/8456698/25656222/938e1788-302a-11e7-9d8f-c27f53e7469c.png)

**Comment by lguipeng** [comment]
Show me your xml layout, and send me this photo .

**Comment by JarvanChen** [comment]
![image](https://cloud.githubusercontent.com/assets/8456698/26289234/ca870a4c-3ed0-11e7-8fc6-9d1daf9a3e6b.png)
![test](https://cloud.githubusercontent.com/assets/8456698/26289245/eb487bc6-3ed0-11e7-984a-8bf76c3f9045.jpg)

**Comment by lguipeng** [comment]
Look at BubbleDrawable. setUpShaderMatrix(),  you will find the reason and do some centerCrop will fix this.
But the best simple way is that change your android:layout_height="240dp" to wrap_content.

**Comment by JarvanChen** [comment]
![image](https://cloud.githubusercontent.com/assets/8456698/26291445/ebf5c5a0-3ee0-11e7-8bd8-1af914753f9f.png)

**Comment by lguipeng** [comment]
update  mShaderMatrix.postScale(scale, scale) to mShaderMatrix.postScale(scaleX, scaleY) can fix this.

**Comment by SwordChen518** [comment]
Ok, thank you for your response. I think it should be ok
