### ISSUE TITLE
怎么加边框

### ISSUE THREAD

**Issue by kanglanlan** [lguipeng/BubbleView#12]

**Comment by kanglanlan** [comment]
怎么加个边框

**Comment by lguipeng** [comment]
目前不支持

**Comment by caprice** [comment]
相当不错的library. 但是边框这个是正常需要吧，应该考虑支持的。

**Comment by lguipeng** [comment]
这个实现起来并不难，因为path 我已经规划好了，然后利用 rect.inset(dx, dy)，最后用画笔画边框就行了，有时间的话我会完善上去的 @kanglanlan @caprice
