### ISSUE TITLE
请问BubbleView如何搭配fresco使用

### ISSUE THREAD

**Issue by ixxxxxx** [lguipeng/BubbleView#15]
我的第一反应是在`BubbleLinearLayout`嵌套`SimpleDraweeView`，但是`SimpleDraweeView`会把`BubbleLinearLayout`生成的气泡给覆盖掉，这样还是只显示图片，有什么办法可以搭配fresco使用吗？

**Comment by lguipeng** [comment]
fresco 的话，可以用设置监听 获取 bitmap。然后给imageview 设置上，不过你也可以考虑 fresco setPostprocessor 的方式
