### ISSUE TITLE
BubleLinearLayout  Size when used in adapter 

### ISSUE THREAD

**Issue by raviteja83** [lguipeng/BubbleView#3]
When used in Adapter bubble layout size when once increased all the other views also increase to same size irrespective of the content

**Comment by lguipeng** [comment]
Change the child views of BubleLinearLayout dynamically?

**Comment by Dagzo** [comment]
Hi lguipeng.

I have same issue.
In case of me, ReyclerView.

>Change the child views of BubbleLinearLayout dynamically?
Yes, my list items has BubbleLinearLayout as parent of TableLayout.
The TableLayout get some TableRow that contains ImageView dynamically.
After TableRow increased, BubbleLinearLayout size changed.
But after that, other BubbleLinearLayout size also changed.

How can I control the size? 
Regards,
